import type { FaqItem, ToolDef } from "./tools";

const local: FaqItem = {
  q: "Is anything uploaded?",
  a: "No. This tool runs in your browser tab. Close it and the data is gone.",
};

function t(
  slug: string,
  name: string,
  category: ToolDef["category"],
  mode: ToolDef["mode"],
  kicker: string,
  h1: string,
  lede: string,
  keywords: string[],
  faqs: FaqItem[],
  related: string[],
): ToolDef {
  return {
    slug,
    name,
    category,
    mode,
    kicker,
    h1,
    lede,
    metaTitle: `${name} Free – Cherry Converter`,
    metaDescription: `${lede} On your device. No account.`,
    keywords,
    faqs: [...faqs, local],
    related,
  };
}

export const P0_TOOLS: ToolDef[] = [
  t("color-picker", "Color Picker", "color", "color-studio", "Color  /  Picker", "Color picker in your browser", "Eyedrop from the screen or an image. HEX, RGB, HSL, HSV, CMYK (approx), OKLCH. File stays on this device.", ["color picker", "color picker from image", "hex color picker"], [{ q: "Screen dropper?", a: "Chromium EyeDropper API. Elsewhere, paste hex or click a dropped image." }], ["hex-to-rgb", "contrast-checker", "color-palette-from-image"]),
  t("hex-to-rgb", "HEX to RGB", "color", "color-studio", "Color  /  HEX", "Convert HEX to RGB in your browser", "Paste #F2013F and get RGB, HSL, HSV, approximate CMYK, and OKLCH. No upload.", ["hex to rgb", "hex to rgb converter", "convert hex to rgb"], [{ q: "3-digit hex?", a: "Yes. #f20 expands to #ff2200." }], ["rgb-to-hex", "color-picker", "contrast-checker"]),
  t("rgb-to-hex", "RGB to HEX", "color", "color-studio", "Color  /  RGB", "Convert RGB to HEX in your browser", "Type rgb(242, 1, 63) or components. Copy CSS, Tailwind, Swift, Android.", ["rgb to hex", "rgb to hex converter"], [{ q: "HSL too?", a: "hsl() strings parse. Output is always #rrggbb." }], ["hex-to-rgb", "color-picker", "gradient-generator"]),
  t("contrast-checker", "WCAG Contrast Checker", "color", "color-studio", "Color  /  WCAG", "WCAG 2.2 contrast checker", "Normal text, large text, UI components. AA / AAA. Suggests a nearby passing color. Local.", ["contrast checker WCAG", "wcag contrast", "accessible contrast checker"], [{ q: "WCAG 2.2?", a: "Text uses 4.5:1 AA and 7:1 AAA. UI non-text uses 3:1. Not a full audit." }], ["color-picker", "color-palette-from-image", "hex-to-rgb"]),
  t("color-palette-from-image", "Color Palette from Image", "color", "color-studio", "Color  /  Palette", "Build a color palette from an image", "Samples pixels in this tab. Complementary, analogous, monochrome, Tailwind-like scale.", ["color palette from image", "accessible color palette", "extract colors from photo"], [{ q: "Is this Adobe Color?", a: "No. It buckets pixel colours locally. Not a generative brand system." }], ["color-picker", "contrast-checker", "gradient-generator"]),
  t("gradient-generator", "CSS Gradient Generator", "color", "color-studio", "Color  /  Gradient", "CSS gradient generator", "Two stops, live preview, copy CSS. Runs here.", ["css gradient generator", "linear gradient generator"], [{ q: "Mesh?", a: "Linear two-stop only." }], ["color-picker", "hex-to-rgb", "color-palette-from-image"]),

  t("time-zone-converter", "Time Zone Converter", "time", "time-studio", "Time  /  Zones", "Convert EST to GMT and any IANA zone", "DST-aware conversion for US, UK, India, UAE, AU and more. Timestamp stays in this tab.", ["est to gmt", "time zone converter", "pst to ist", "gmt to est"], [{ q: "EST or America/New_York?", a: "We use IANA IDs. New York follows US DST. EST as a fixed offset is not used." }], ["meeting-planner", "world-clock", "unix-timestamp-converter"]),
  t("meeting-planner", "Meeting Planner", "time", "time-studio", "Time  /  Meeting", "Meeting planner across time zones", "Pick 2–8 cities. Hours that sit in 09:00–18:00 locally are listed. Best slot this week.", ["meeting time US UK India", "meeting planner time zones", "what time in dubai now"], [{ q: "Work hours?", a: "Fixed 09:00–18:00 local. No calendar API." }], ["time-zone-converter", "world-clock", "business-days-calculator"]),
  t("world-clock", "World Clock", "time", "time-studio", "Time  /  Clock", "World clock for T1 and T2 cities", "New York, London, Dubai, Delhi, Sydney, Tokyo and more. Offsets from this browser.", ["world clock", "what time in dubai now", "time in singapore"], [{ q: "Live seconds?", a: "Refreshes about every 30 seconds." }], ["time-zone-converter", "meeting-planner", "unix-timestamp-converter"]),

  t("age-calculator", "Age Calculator", "time", "date-studio", "Date  /  Age", "Age calculator from date of birth", "Years, months, days, and next birthday. Dates stay on this device.", ["age calculator", "age from date of birth"], [{ q: "Leap days?", a: "Uses calendar months, not 365.25." }], ["date-difference", "business-days-calculator", "unix-timestamp-converter"]),
  t("date-difference", "Date Difference", "time", "date-studio", "Date  /  Diff", "Days between two dates", "Calendar span, ISO week number, add/subtract days months years.", ["date difference", "days between dates", "date calculator"], [{ q: "Inclusive?", a: "End minus start in midnights UTC. Same day is 0." }], ["age-calculator", "business-days-calculator", "unix-timestamp-converter"]),
  t("business-days-calculator", "Business Days Calculator", "time", "date-studio", "Date  /  Business", "Business days calculator", "Skips Saturday and Sunday. Optional US / UK / UAE / India sample holidays — not a gazette.", ["business days calculator", "working days between dates"], [{ q: "Official holidays?", a: "Sample packs only. Confirm against the government calendar." }], ["date-difference", "meeting-planner", "age-calculator"]),
  t("unix-timestamp-converter", "Unix Timestamp Converter", "time", "date-studio", "Date  /  Unix", "Unix timestamp to date", "Seconds since epoch ↔ ISO 8601. Local.", ["unix timestamp converter", "epoch converter"], [{ q: "Milliseconds?", a: "This page is seconds. Divide ms by 1000." }], ["time-zone-converter", "date-difference", "jwt-decoder"]),

  t("uuid-generator", "UUID Generator", "developer", "dev-studio", "Dev  /  UUID", "UUID v4 and v7 generator", "Bulk 1–100. Crypto.getRandomValues in this tab.", ["uuid generator", "uuid v4", "uuid v7 generator"], [{ q: "v7?", a: "Unix-ms prefix plus random. Sortable. Not a database default." }], ["sha256-hash", "regex-tester", "jwt-decoder"]),
  t("sha256-hash", "SHA-256 Hash", "developer", "dev-studio", "Dev  /  Hash", "SHA-256 of text or a file on your device", "SubtleCrypto SHA-256 and SHA-1. MD5 is labelled checksum only. Drop a PDF — it is not uploaded.", ["sha256 hash", "sha-256 of file", "hash file on device"], [{ q: "MD5?", a: "Shown as a checksum. Do not use MD5 for passwords." }], ["md5-checksum", "hmac-sha256", "uuid-generator"]),
  t("md5-checksum", "MD5 Checksum", "developer", "dev-studio", "Dev  /  MD5", "MD5 checksum (not security)", "Checksum a string or file locally. Not for security.", ["md5 checksum", "md5 hash file"], [{ q: "Secure?", a: "No. Collision-prone. Use SHA-256." }], ["sha256-hash", "hmac-sha256", "uuid-generator"]),
  t("hmac-sha256", "HMAC-SHA256", "developer", "dev-studio", "Dev  /  HMAC", "HMAC-SHA256 in the browser", "Key and message stay in this tab.", ["hmac sha256", "hmac generator"], [{ q: "Key uploaded?", a: "No." }], ["sha256-hash", "jwt-decoder", "uuid-generator"]),
  t("regex-tester", "Regex Tester", "developer", "dev-studio", "Dev  /  Regex", "Regex tester in your browser", "Match, groups, replace. JavaScript RegExp. No server.", ["regex tester", "regexp tester", "regex replace online"], [{ q: "Flavor?", a: "JavaScript. Not PCRE or .NET." }], ["jwt-decoder", "uuid-generator", "json-formatter"]),
  t("jwt-decoder", "JWT Decoder", "developer", "dev-studio", "Dev  /  JWT", "Decode a JWT header and payload", "Base64url decode only. Signature is not verified. There is no key server.", ["jwt decoder", "decode jwt", "jwt debugger"], [{ q: "Verify signature?", a: "No. Verification would need a key. We will not send the token anywhere to check it." }], ["regex-tester", "base64-encoder-decoder", "sha256-hash"]),

  t(
    "pdf-metadata-remover",
    "PDF Metadata Remover",
    "pdf",
    "pdf-studio",
    "PDF  /  Metadata",
    "Strip PDF metadata and XMP in your browser",
    "Clears title, author, dates, and the Info dictionary. Encrypted PDFs may fail. File never uploaded.",
    ["strip pdf metadata", "remove pdf xmp", "pdf metadata remover"],
    [{ q: "Hidden text?", a: "This is metadata only. Use a redaction tool for body text." }],
    ["exif-metadata-remover", "pdf-merger", "compress-pdf"],
  ),
  {
    slug: "wifi-speed-test",
    name: "Wi‑Fi Speed Test",
    category: "developer",
    mode: "speed-test",
    kicker: "Network  /  Speed",
    h1: "Wi‑Fi / internet speed test",
    lede: "Ping, download, and upload against Cloudflare’s public speed-test host. Generated bytes only — your photos and PDFs never leave this tab.",
    metaTitle: "Wi‑Fi Speed Test Free – Cherry Converter",
    metaDescription:
      "Check download, upload, ping, and jitter in your browser. Talks to Cloudflare’s speed-test host with random bytes. No account. Your files are not uploaded.",
    keywords: [
      "wifi speed test",
      "wi-fi speed test",
      "internet speed test",
      "bandwidth test",
      "speed test checker",
      "download speed test",
    ],
    faqs: [
      {
        q: "Does this upload my files?",
        a: "No. The test posts generated random bytes to measure upload. It does not read your photos, PDFs, or camera roll.",
      },
      {
        q: "Is this 100% local like the image tools?",
        a: "No. A speed test has to talk to a remote host. This page uses Cloudflare speed.cloudflare.com. Image and PDF tools on Cherry Converter still never leave the device.",
      },
      {
        q: "Wi‑Fi or Ethernet?",
        a: "It measures this device’s path to Cloudflare. If you are on Wi‑Fi, that hop is included. It is not a lab certification of your access point.",
      },
      {
        q: "Why do you show an IP?",
        a: "Cloudflare’s trace file can include the public IP they see. It is displayed here, not stored by Cherry Converter.",
      },
    ],
    related: ["world-clock", "time-zone-converter", "qr-code-generator"],
  },
  t(
    "spin-the-wheel",
    "Spin the Wheel",
    "utilities",
    "chance",
    "Chance  /  Wheel",
    "Spin the wheel — random picker in your browser",
    "Add names or choices, spin, get one winner. Slices are equal unless you set a ratio.",
    ["spin the wheel", "random wheel picker", "decision wheel", "wheel of names"],
    [
      { q: "Equal parts or ratio?", a: "One option per line is an equal slice. A bigger slice: Pizza x3 or No:2. The spin lands in proportion to those weights." },
      { q: "Saved lists?", a: "Not across visits. Paste your list each time, or keep it in a text file." },
    ],
    ["coin-toss", "uuid-generator", "mouse-checker"],
  ),
  t(
    "coin-toss",
    "Coin Toss",
    "utilities",
    "chance",
    "Chance  /  Toss",
    "Coin toss — heads or tails",
    "Heads or tails.",
    ["coin toss", "flip a coin", "heads or tails", "toss a coin"],
    [{ q: "Fair flip?", a: "Each toss is heads or tails with equal chance." }],
    ["spin-the-wheel", "uuid-generator", "mouse-checker"],
  ),
  t(
    "mouse-checker",
    "Mouse Checker",
    "utilities",
    "mouse-check",
    "Hardware  /  Mouse",
    "Mouse checker — buttons, clicks, scroll, trail",
    "Test left/right/middle/back/forward, CPS, double-click gap, and movement. Events stay in this tab.",
    ["mouse checker", "mouse tester", "mouse click tester", "check mouse buttons"],
    [
      { q: "DPI?", a: "Browsers do not expose true DPI. You get pixels, buttons, and click timing." },
      { q: "Right-click menu?", a: "Disabled on this page so button 2 can be tested." },
    ],
    ["wifi-speed-test", "spin-the-wheel", "coin-toss"],
  ),
  {
    slug: "server-down-checker",
    name: "Server Down Checker",
    category: "utilities",
    mode: "status-check",
    kicker: "Network  /  Down",
    h1: "Is the server down? Check from this browser",
    lede: "Reachability from your device only — not a global outage map. Cherry Converter does not proxy or log the URL. Your files are not sent.",
    metaTitle: "Is the Server Down? Website Checker Free – Cherry Converter",
    metaDescription:
      "Check if a website is reachable from your browser. No proxy, no account. Not a worldwide outage feed. Files are never uploaded.",
    keywords: [
      "server down",
      "is the server down",
      "website down checker",
      "is it down",
      "is this site down",
    ],
    faqs: [
      {
        q: "Is this downforeveryoneorjustme?",
        a: "No. That kind of service checks from their servers. This page only uses your browser. If it loads for you, it is not down for you.",
      },
      {
        q: "Do you log the URL?",
        a: "No. There is no status API. Your browser talks to the host you typed.",
      },
      {
        q: "CORS failure?",
        a: "Many sites hide HTTP status from other origins. An opaque response still means something answered. A network error can be down, DNS, mixed content, or a firewall.",
      },
      {
        q: "Are my files uploaded?",
        a: "No. This is not a file tool.",
      },
    ],
    related: ["wifi-speed-test", "time-zone-converter", "mouse-checker"],
  },
  t(
    "url-media-downloader",
    "URL Media Downloader",
    "convert",
    "url-media",
    "URL  /  Media",
    "Download or convert media from a public URL",
    "Paste a link. We detect the platform and list public files only — direct mp4/webm/mp3/images/PDF, pages that advertise a real og:video file, Reddit image host, official thumbnails. No DRM bypass, no fake YouTube rip.",
    [
      "url downloader",
      "download from url",
      "media url converter",
      "download mp4 from url",
      "direct video download",
    ],
    [
      { q: "YouTube / TikTok video file?", a: "No. A watch URL is a player page, not an mp4. We show the title and public thumbnail. We do not rip the player, decode googlevideo streams, or fake a 4K download button. Watch or download in the official app if that platform offers it." },
      { q: "What does work?", a: "Direct file URLs (mp4, webm, mov, mp3, jpg, png, webp, gif, pdf), HTML pages that advertise a real video file (Open Graph og:video or JSON-LD contentUrl pointing at mp4/webm), i.redd.it images, YouTube thumbnail CDN, official oEmbed thumbnails. Then download the original or re-encode video to WebM / save a first frame in this tab." },
      { q: "Is the file uploaded to Cherry Converter?", a: "The inspect/fetch API retrieves a public URL you pasted (with SSRF blocks, 48 MB cap). Your camera roll is not read. Image convert and video re-encode then run in this tab." },
    ],
    ["supported-platforms", "convert", "youtube-url-tools"],
  ),
  t(
    "supported-platforms",
    "Supported Platforms",
    "convert",
    "url-media",
    "URL  /  Platforms",
    "Supported platforms for URL detection",
    "Modular adapters for YouTube, TikTok, Instagram, X, Reddit, Vimeo, and 20+ more. Detection is not the same as download. Stream ripping is not offered.",
    ["supported platforms downloader", "url downloader platforms"],
    [{ q: "Why detect if you cannot download?", a: "So the page tells the truth instead of showing a fake 4K button." }],
    ["url-media-downloader", "youtube-url-tools", "tiktok-url-tools"],
  ),
  t(
    "youtube-url-tools",
    "YouTube URL Tools",
    "convert",
    "url-media",
    "URL  /  YouTube",
    "YouTube URL tools — thumbnail and metadata",
    "Paste a YouTube or Shorts URL. Public thumbnails via i.ytimg.com. Video file download is not offered (YouTube terms / no public stream).",
    ["youtube thumbnail download", "youtube url tools", "youtube shorts thumbnail"],
    [
      { q: "Can I download the video from a YouTube link?", a: "No. YouTube does not publish a public video file for other sites. We save the public thumbnail only. Use YouTube itself if they offer a download." },
      { q: "4K video download?", a: "No. That would mean ripping the player. We will not fake it." },
    ],
    ["url-media-downloader", "supported-platforms", "tiktok-url-tools"],
  ),
  t(
    "tiktok-url-tools",
    "TikTok URL Tools",
    "convert",
    "url-media",
    "URL  /  TikTok",
    "TikTok URL tools — public preview only",
    "Detect a TikTok URL and show official oEmbed metadata/thumbnail when available. We do not bypass TikTok download restrictions.",
    ["tiktok url tools", "tiktok thumbnail"],
    [{ q: "Save the mp4?", a: "Not unless you paste a direct public file URL. The watch page is not a file." }],
    ["url-media-downloader", "youtube-url-tools", "instagram-url-tools"],
  ),
  t(
    "instagram-url-tools",
    "Instagram URL Tools",
    "convert",
    "url-media",
    "URL  /  Instagram",
    "Instagram URL tools — no private/login bypass",
    "Instagram posts require their app/login for the media file. This page detects the URL and refuses fake download buttons.",
    ["instagram url tools", "instagram media url"],
    [{ q: "Reel download?", a: "Not supported. Private and login-gated media stay gated." }],
    ["url-media-downloader", "tiktok-url-tools", "facebook-url-tools"],
  ),
  t(
    "facebook-url-tools",
    "Facebook URL Tools",
    "convert",
    "url-media",
    "URL  /  Facebook",
    "Facebook URL tools",
    "Detect Facebook / fb.watch links. No login bypass, no DRM player rip.",
    ["facebook url tools", "fb.watch"],
    [{ q: "Public video file?", a: "Facebook does not give third parties a clean mp4. Paste a direct file if you have one." }],
    ["url-media-downloader", "instagram-url-tools", "twitter-url-tools"],
  ),
  t(
    "twitter-url-tools",
    "X / Twitter URL Tools",
    "convert",
    "url-media",
    "URL  /  X",
    "X (Twitter) URL tools",
    "Detect x.com / twitter.com links. Media files behind the player are not ripped.",
    ["twitter url tools", "x.com video", "twitter media"],
    [{ q: "GIF/video?", a: "Only if you have a direct media URL. The status page is not a file." }],
    ["url-media-downloader", "facebook-url-tools", "reddit-url-tools"],
  ),
  t(
    "reddit-url-tools",
    "Reddit URL Tools",
    "convert",
    "url-media",
    "URL  /  Reddit",
    "Reddit URL tools — i.redd.it images",
    "Direct Reddit image hosts can be fetched. v.redd.it player streams are not ripped.",
    ["reddit image download", "i.redd.it", "reddit url tools"],
    [{ q: "v.redd.it?", a: "That is a player stream, not offered here." }],
    ["url-media-downloader", "twitter-url-tools", "convert"],
  ),
  t(
    "vimeo-url-tools",
    "Vimeo URL Tools",
    "convert",
    "url-media",
    "URL  /  Vimeo",
    "Vimeo URL tools — oEmbed preview",
    "Official oEmbed title and thumbnail. Password and private videos stay private.",
    ["vimeo url tools", "vimeo thumbnail"],
    [{ q: "Source file?", a: "Vimeo does not hand us the master file. Thumbnails only unless you paste a direct URL." }],
    ["url-media-downloader", "youtube-url-tools", "soundcloud-url-tools"],
  ),
  t(
    "pinterest-url-tools",
    "Pinterest URL Tools",
    "convert",
    "url-media",
    "URL  /  Pinterest",
    "Pinterest URL tools",
    "Detect pin.it / pinterest.com. We do not scrape logged-in boards.",
    ["pinterest url tools", "pin.it"],
    [{ q: "Original pin image?", a: "Only a direct image URL. The pin page is not a file." }],
    ["url-media-downloader", "instagram-url-tools", "convert"],
  ),
  t(
    "soundcloud-url-tools",
    "SoundCloud URL Tools",
    "convert",
    "url-media",
    "URL  /  SoundCloud",
    "SoundCloud URL tools — oEmbed preview",
    "Official oEmbed metadata. Audio stream ripping is not offered.",
    ["soundcloud url tools", "soundcloud thumbnail"],
    [{ q: "MP3?", a: "Not from the watch page. Paste a direct audio file URL to convert." }],
    ["url-media-downloader", "vimeo-url-tools", "youtube-url-tools"],
  ),
  t(
    "ats-resume-builder",
    "ATS Resume Builder",
    "text",
    "ats-resume",
    "Text  /  Resume",
    "CherryResume — ATS kit, free in this tab",
    "CherryResume is an ATS-first engine, not a pretty-template writer. Live US Letter preview matches PDF and Word. JD intelligence (P0–P3), gap analysis, truth-labeled bullets, CherryScore with ATS risk — all in this browser. Unproven keywords are never stuffed. No invented jobs or metrics. CherryScore is not a vendor ATS score.",
    [
      "ats resume builder",
      "cherryresume",
      "resume builder",
      "ats friendly resume",
      "resume pdf",
      "resume word",
      "cover letter",
      "cv builder",
      "rezi alternative",
      "teal alternative",
    ],
    [
      { q: "Will this get me 90+ ATS?", a: "No vendor score is promised. CherryScore is an internal heuristic (parse, JD match, experience, content, scan, truth) plus ATS risk. It is not Workday, Taleo, or Greenhouse." },
      { q: "Is my resume uploaded?", a: "No. It stays in this browser (localStorage). Close the tab or clear site data to drop it." },
      { q: "Why no photo or two columns?", a: "Many parsers skip tables, text boxes, and sidebars. This builder refuses those on purpose." },
      { q: "Does the preview match PDF and Word?", a: "Yes. The live page is US Letter. Classic, Compact, and Executive change font and spacing in the preview and in the downloaded files. Names, titles, and bullets are formatted automatically." },
      { q: "Will you write a 90+ resume from a blank JD?", a: "No. P0 skills without proof stay on Do not add. Cover letter, email, and LinkedIn use only VERIFIED fields." },
      { q: "Does Improve with AI upload my resume?", a: "Only when you click it. Wording is rewritten for the JD and written back into the form. New jobs, dates, and numbers are stripped if the model invents them. Tailor on this device never leaves the browser." },
    ],
    ["word-counter", "pdf-to-word", "ocr-image-to-text"],
  ),
];
