/**
 * Measures this device's path to a public speed-test host.
 * Sends only generated bytes — never user files.
 * Host: Cloudflare speed.cloudflare.com (same endpoints as their public test).
 */

export type SpeedProgress = {
  phase: "idle" | "ping" | "download" | "upload" | "done" | "error";
  pingMs?: number;
  jitterMs?: number;
  downloadMbps?: number;
  uploadMbps?: number;
  loadedBytes?: number;
  note?: string;
};

export type SpeedResult = {
  pingMs: number;
  jitterMs: number;
  downloadMbps: number;
  uploadMbps: number;
  colo?: string;
  loc?: string;
  ipHint?: string;
};

const DOWN = "https://speed.cloudflare.com/__down";
const UP = "https://speed.cloudflare.com/__up";
const TRACE = "https://speed.cloudflare.com/cdn-cgi/trace";

function mbps(bytes: number, ms: number): number {
  if (ms <= 0) return 0;
  return (bytes * 8) / (ms / 1000) / 1_000_000;
}

function median(values: number[]): number {
  if (!values.length) return 0;
  const s = [...values].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
}

function jitter(values: number[]): number {
  if (values.length < 2) return 0;
  const diffs: number[] = [];
  for (let i = 1; i < values.length; i += 1) diffs.push(Math.abs(values[i] - values[i - 1]));
  return median(diffs);
}

export function formatMbps(n?: number | null): string {
  if (n == null || n <= 0) return "—";
  if (n >= 100) return `${n.toFixed(0)} Mbps`;
  return `${n.toFixed(1)} Mbps`;
}

export function formatMs(n?: number | null): string {
  if (n == null || n <= 0) return "—";
  return `${Math.round(n)} ms`;
}

export async function pingOnce(signal: AbortSignal): Promise<number> {
  const t0 = performance.now();
  const res = await fetch(`${DOWN}?bytes=0&r=${Math.random()}`, {
    cache: "no-store",
    credentials: "omit",
    signal,
  });
  await res.arrayBuffer();
  return performance.now() - t0;
}

export async function downloadOnce(bytes: number, signal: AbortSignal): Promise<{ bytes: number; ms: number }> {
  const t0 = performance.now();
  const res = await fetch(`${DOWN}?bytes=${bytes}&r=${Math.random()}`, {
    cache: "no-store",
    credentials: "omit",
    signal,
  });
  const buf = await res.arrayBuffer();
  return { bytes: buf.byteLength, ms: performance.now() - t0 };
}

export async function uploadOnce(bytes: number, signal: AbortSignal): Promise<{ bytes: number; ms: number }> {
  const body = new Uint8Array(bytes);
  crypto.getRandomValues(body.subarray(0, Math.min(65536, bytes)));
  const t0 = performance.now();
  const res = await fetch(UP, {
    method: "POST",
    cache: "no-store",
    credentials: "omit",
    signal,
    body,
    headers: { "content-type": "application/octet-stream" },
  });
  await res.arrayBuffer();
  return { bytes, ms: performance.now() - t0 };
}

export async function readTrace(signal: AbortSignal): Promise<{ colo?: string; loc?: string; ipHint?: string }> {
  try {
    const res = await fetch(`${TRACE}?r=${Math.random()}`, { cache: "no-store", credentials: "omit", signal });
    const text = await res.text();
    const get = (key: string) => text.match(new RegExp(`(?:^|\\n)${key}=([^\\n]+)`))?.[1];
    return { colo: get("colo"), loc: get("loc"), ipHint: get("ip") };
  } catch {
    return {};
  }
}

export async function runSpeedTest(
  onProgress: (p: SpeedProgress) => void,
  signal: AbortSignal,
): Promise<SpeedResult> {
  onProgress({ phase: "ping", note: "Measuring latency to Cloudflare…" });
  const pings: number[] = [];
  for (let i = 0; i < 6; i += 1) {
    pings.push(await pingOnce(signal));
    onProgress({
      phase: "ping",
      pingMs: median(pings),
      jitterMs: jitter(pings),
      note: `Ping sample ${i + 1}/6`,
    });
  }
  const pingMs = median(pings);
  const jitterMs = jitter(pings);

  onProgress({ phase: "download", pingMs, jitterMs, note: "Downloading random bytes…" });
  const downSizes = pingMs > 80 ? [1_000_000, 5_000_000] : [2_000_000, 10_000_000, 25_000_000];
  let bestDown = 0;
  let loaded = 0;
  for (const size of downSizes) {
    const { bytes, ms } = await downloadOnce(size, signal);
    loaded += bytes;
    const rate = mbps(bytes, ms);
    if (rate > bestDown) bestDown = rate;
    onProgress({
      phase: "download",
      pingMs,
      jitterMs,
      downloadMbps: bestDown,
      loadedBytes: loaded,
      note: `Download ${rate.toFixed(1)} Mbps`,
    });
  }

  onProgress({
    phase: "upload",
    pingMs,
    jitterMs,
    downloadMbps: bestDown,
    note: "Uploading generated bytes (not your files)…",
  });
  const upSizes = pingMs > 80 ? [250_000, 750_000] : [500_000, 2_000_000];
  let bestUp = 0;
  for (const size of upSizes) {
    const { bytes, ms } = await uploadOnce(size, signal);
    const rate = mbps(bytes, ms);
    if (rate > bestUp) bestUp = rate;
    onProgress({
      phase: "upload",
      pingMs,
      jitterMs,
      downloadMbps: bestDown,
      uploadMbps: bestUp,
      note: `Upload ${rate.toFixed(1)} Mbps`,
    });
  }

  const meta = await readTrace(signal);
  onProgress({
    phase: "done",
    pingMs,
    jitterMs,
    downloadMbps: bestDown,
    uploadMbps: bestUp,
    note: "Done. This is the path to Cloudflare, not a lab-certified Wi‑Fi meter.",
  });
  return { pingMs, jitterMs, downloadMbps: bestDown, uploadMbps: bestUp, ...meta };
}

export type LiveSample = {
  pingMs: number;
  jitterMs: number;
  downloadMbps: number | null;
  uploadMbps: number | null;
};

/** One lightweight probe. Never reads user files. */
export async function liveSample(
  signal: AbortSignal,
  opts: { down?: boolean; up?: boolean; downBytes?: number; upBytes?: number },
  pingWindow: number[],
): Promise<LiveSample> {
  const ping = await pingOnce(signal);
  pingWindow.push(ping);
  if (pingWindow.length > 16) pingWindow.shift();
  let downloadMbps: number | null = null;
  let uploadMbps: number | null = null;
  if (opts.down) {
    const d = await downloadOnce(opts.downBytes ?? 180_000, signal);
    downloadMbps = mbps(d.bytes, d.ms);
  }
  if (opts.up) {
    const u = await uploadOnce(opts.upBytes ?? 60_000, signal);
    uploadMbps = mbps(u.bytes, u.ms);
  }
  return {
    pingMs: median(pingWindow),
    jitterMs: jitter(pingWindow),
    downloadMbps,
    uploadMbps,
  };
}

export function connectionHint(): string | null {
  if (typeof navigator === "undefined") return null;
  const nav = navigator as Navigator & {
    connection?: { downlink?: number; effectiveType?: string; rtt?: number };
  };
  const c = nav.connection;
  if (!c) return null;
  const bits = [
    c.effectiveType ? `browser hint ${c.effectiveType}` : null,
    c.downlink != null ? `~${c.downlink} Mbps downlink API` : null,
    c.rtt != null ? `${c.rtt} ms rtt API` : null,
  ].filter(Boolean);
  return bits.length ? `${bits.join(" · ")} (Network Information API, not the test)` : null;
}
