import type { FaqItem, ToolDef } from "./tools";

const local: FaqItem = {
  q: "Is my file uploaded?",
  a: "No. Work runs in this browser tab. Close it and the file is gone.",
};

function t(
  slug: string,
  name: string,
  category: ToolDef["category"],
  mode: ToolDef["mode"],
  kicker: string,
  h1: string,
  lede: string,
  keywords: string[],
  faqs: FaqItem[],
  related: string[],
  extra?: Partial<ToolDef>,
): ToolDef {
  return {
    slug,
    name,
    category,
    mode,
    kicker,
    h1,
    lede,
    metaTitle: `${name} Online Free – Cherry Converter`,
    metaDescription: `${lede} Runs in your browser. No upload.`,
    keywords,
    faqs: [...faqs, local],
    related,
    ...extra,
  };
}

export const UTILITY_TOOLS: ToolDef[] = [
  t(
    "pdf-merger",
    "PDF Merger",
    "pdf",
    "pdf-studio",
    "PDF  /  Merge",
    "Merge PDFs in your browser",
    "Combine several PDFs into one file, in order. Pages are copied, not re-rasterised. Nothing is uploaded.",
    ["pdf merger", "merge pdf", "combine pdf", "join pdf files"],
    [
      { q: "Will quality drop?", a: "No. Pages are copied with pdf-lib in this tab. Encrypted PDFs may fail." },
      { q: "Is there a page cap?", a: "Only your device memory. Large scans can stall a phone; a desktop is safer." },
    ],
    ["pdf-splitter", "pdf-page-extractor", "jpg-to-pdf"],
    { multiple: true },
  ),
  t(
    "pdf-splitter",
    "PDF Splitter",
    "pdf",
    "pdf-studio",
    "PDF  /  Split",
    "Split a PDF into single pages",
    "One PDF in, one file per page out — or a ZIP. Split locally.",
    ["pdf splitter", "split pdf", "separate pdf pages"],
    [{ q: "Do I get one file or a ZIP?", a: "A single page downloads as a PDF. Several pages come as a ZIP." }],
    ["pdf-merger", "pdf-page-extractor", "pdf-to-png"],
  ),
  t(
    "pdf-page-extractor",
    "PDF Page Extractor",
    "pdf",
    "pdf-studio",
    "PDF  /  Extract",
    "Extract PDF pages by range",
    "Type 1-3, 5, 8 and download those pages as a new PDF. Local, no upload.",
    ["extract pdf pages", "pdf page extractor", "save pdf pages"],
    [{ q: "What range syntax?", a: "Comma-separated pages and ranges: 1-3, 5, 8-9. Numbers are 1-based." }],
    ["pdf-splitter", "pdf-merger", "pdf-to-png"],
  ),
  t(
    "pdf-to-word",
    "PDF to Word",
    "pdf",
    "pdf-studio",
    "PDF  /  Word",
    "Convert PDF to Word in the browser",
    "Extracts the text layer into a .docx. Scanned pages can be OCRed on this device. This is not Adobe’s layout-perfect conversion.",
    ["pdf to word", "pdf to docx", "convert pdf to word"],
    [
      {
        q: "Will columns and images look like Word?",
        a: "No. You get the text (and OCR if you tick it) in a real .docx. Logos, exact fonts, and multi-column layout stay in the PDF.",
      },
      {
        q: "Does OCR upload the scan?",
        a: "No. Tesseract runs in WebAssembly. It may download a public English language model; your PDF stays in the tab.",
      },
    ],
    ["pdf-to-text", "pdf-to-excel", "ocr-image-to-text"],
  ),
  t(
    "pdf-to-excel",
    "PDF to Excel",
    "pdf",
    "pdf-studio",
    "PDF  /  Excel",
    "Convert PDF to Excel in the browser",
    "Groups on-page text into columns and writes an .xlsx. Tables with a real text layer work; scans need OCR.",
    ["pdf to excel", "pdf to xlsx", "extract table from pdf"],
    [
      {
        q: "Is every table perfect?",
        a: "No. We cluster text by position. Merged cells and scanned receipts will need a pass in Excel.",
      },
    ],
    ["pdf-to-word", "pdf-to-text", "ocr-image-to-text"],
  ),
  t(
    "pdf-to-png",
    "PDF to PNG",
    "pdf",
    "pdf-studio",
    "PDF  /  PNG",
    "Convert PDF pages to PNG",
    "Rasterise each page to a PNG in this tab. One page downloads directly; several come as a ZIP.",
    ["pdf to png", "pdf to image", "convert pdf pages to png"],
    [{ q: "Vector or bitmap?", a: "PNG is a bitmap. Fine for sharing a page; keep the PDF if you still need selectable type." }],
    ["pdf-to-text", "jpg-to-pdf", "pdf-splitter"],
    { multiple: true },
  ),
  t(
    "pdf-to-text",
    "PDF to Text",
    "pdf",
    "pdf-studio",
    "PDF  /  Text",
    "Extract text from a PDF",
    "Copy the text layer, or OCR scanned pages in this browser. Download a .txt.",
    ["pdf to text", "extract text from pdf", "pdf text extractor"],
    [{ q: "Empty output?", a: "The PDF is probably a scan. Tick OCR — English, on this device." }],
    ["pdf-to-word", "ocr-image-to-text", "word-counter"],
  ),
  t(
    "ocr-image-to-text",
    "OCR / Image to Text",
    "text",
    "ocr",
    "OCR  /  English",
    "OCR — image or PDF to text",
    "Read English print from a photo or scan with Tesseract in this tab. A public language model may download; the file does not leave the device.",
    ["ocr online", "image to text", "photo to text", "pdf ocr"],
    [
      {
        q: "Handwriting?",
        a: "Printed Latin type works. Cursive and tiny screenshots often fail. We do not send the image to a cloud OCR API.",
      },
    ],
    ["image-to-text", "pdf-to-text", "pdf-to-word"],
    { multiple: true },
  ),
  t(
    "image-to-text",
    "Image to Text",
    "text",
    "ocr",
    "OCR  /  Photo",
    "Convert an image to text (OCR)",
    "Drop a photo of a page. English OCR runs locally. Same engine as the OCR tool.",
    ["image to text", "picture to text", "extract text from image"],
    [{ q: "Which languages?", a: "English in this version. The traineddata file comes from a public CDN." }],
    ["ocr-image-to-text", "pdf-to-text", "word-counter"],
  ),
  t(
    "qr-code-generator",
    "QR Code Generator",
    "codes",
    "codes",
    "Codes  /  QR",
    "Generate a QR code",
    "URL, Wi-Fi, vCard, WhatsApp, email, SMS, geo, event. PNG, SVG, PDF. Payload stays in this tab.",
    ["qr code generator", "wifi qr code", "vcard qr code", "qr svg"],
    [
      { q: "Wi-Fi and vCard?", a: "WIFI: and VCARD payloads are built locally. A centre logo forces error-correction H." },
      { q: "Logo in the middle?", a: "Optional. Keep it small so scanners still read the code." },
    ],
    ["qr-code-scanner", "barcode-generator", "url-encoder-decoder"],
  ),
  t(
    "qr-code-scanner",
    "QR Code Scanner",
    "codes",
    "codes",
    "Codes  /  Scan",
    "Scan a QR code from image or camera",
    "Drop a screenshot or use the camera. Decoding stays in this tab.",
    ["qr code scanner", "scan qr code", "read qr code"],
    [{ q: "Does the camera upload video?", a: "No. Frames are read in this tab and the stream stops when a code is found." }],
    ["qr-code-generator", "barcode-scanner", "url-encoder-decoder"],
  ),
  t(
    "barcode-generator",
    "Barcode Generator",
    "codes",
    "codes",
    "Codes  /  Barcode",
    "Generate a barcode",
    "Code 128, Code 39, EAN-13, EAN-8, UPC-A, ITF-14. Download a PNG.",
    ["barcode generator", "code 128 generator", "ean-13 generator"],
    [{ q: "EAN-13 failed?", a: "EAN and UPC need the correct digit length and checksum. Code 128 accepts any text." }],
    ["barcode-scanner", "qr-code-generator"],
  ),
  t(
    "barcode-scanner",
    "Barcode Scanner",
    "codes",
    "codes",
    "Codes  /  Scan",
    "Scan a barcode from a photo",
    "Drop a label photo or use the camera. 1D formats use ZXing in this tab; Chrome can also use the built-in detector.",
    ["barcode scanner", "scan barcode", "ean scanner"],
    [{ q: "Blurry phone shots?", a: "Hold steady, fill the frame, avoid glare. We cannot invent digits that are not in the pixels." }],
    ["barcode-generator", "qr-code-scanner"],
  ),
  t(
    "word-counter",
    "Word Counter",
    "text",
    "text",
    "Text  /  Count",
    "Word counter — in your browser",
    "Words, characters, sentences, paragraphs, and a 200-wpm reading time. Paste stays on this device.",
    ["word counter", "count words", "online word count"],
    [{ q: "How is a word counted?", a: "Whitespace-separated tokens. Hyphenated terms count as one." }],
    ["character-counter", "sentence-counter", "remove-extra-spaces"],
  ),
  t(
    "character-counter",
    "Character Counter",
    "text",
    "text",
    "Text  /  Count",
    "Character counter",
    "Count characters with and without spaces. Same live stats as the word counter.",
    ["character counter", "count characters", "character count online"],
    [{ q: "Does a newline count?", a: "Yes, in the with-spaces total. The no-spaces figure strips all whitespace." }],
    ["word-counter", "sentence-counter", "remove-extra-spaces"],
  ),
  t(
    "sentence-counter",
    "Sentence Counter",
    "text",
    "text",
    "Text  /  Count",
    "Sentence counter",
    "Counts sentences on . ! ? boundaries, plus words and characters.",
    ["sentence counter", "count sentences"],
    [{ q: "Abbreviations?", a: "Mr. and e.g. can inflate the count. It is a punctuation split, not a parser." }],
    ["word-counter", "character-counter", "case-converter"],
  ),
  t(
    "case-converter",
    "Case Converter",
    "text",
    "text",
    "Text  /  Case",
    "Convert text case",
    "UPPER, lower, Title Case, Sentence case, camelCase, snake_case, kebab-case.",
    ["case converter", "uppercase converter", "title case"],
    [{ q: "Title case exceptions?", a: "Every word is capitalised. We do not keep a small-word list (of, the, a)." }],
    ["text-to-slug", "word-counter", "remove-extra-spaces"],
  ),
  t(
    "remove-duplicate-lines",
    "Remove Duplicate Lines",
    "text",
    "text",
    "Text  /  Clean",
    "Remove duplicate lines",
    "Keeps the first copy of each line. Comparison ignores case and surrounding spaces.",
    ["remove duplicate lines", "unique lines", "dedupe text"],
    [{ q: "Blank lines?", a: "The first blank line is kept; later blanks are dropped." }],
    ["remove-extra-spaces", "text-sorter", "word-counter"],
  ),
  t(
    "remove-extra-spaces",
    "Remove Extra Spaces",
    "text",
    "text",
    "Text  /  Clean",
    "Remove extra spaces",
    "Collapse runs of spaces, tidy line breaks, trim the ends.",
    ["remove extra spaces", "trim whitespace", "collapse spaces"],
    [{ q: "Tabs?", a: "Tabs become a single space. Triple newlines become a paragraph break." }],
    ["remove-duplicate-lines", "text-sorter", "word-counter"],
  ),
  t(
    "text-sorter",
    "Text Sorter",
    "text",
    "text",
    "Text  /  Sort",
    "Sort lines of text",
    "Alphabetical, numeric-aware, case-insensitive.",
    ["sort lines", "text sorter", "alphabetize list"],
    [{ q: "Descending?", a: "This page sorts A→Z. Reverse the output with Text Reverser set to Lines." }],
    ["text-reverser", "remove-duplicate-lines", "case-converter"],
  ),
  t(
    "text-reverser",
    "Text Reverser",
    "text",
    "text",
    "Text  /  Reverse",
    "Reverse text, words, or lines",
    "Flip characters, word order, or line order.",
    ["reverse text", "backwards text", "reverse words"],
    [{ q: "Emoji?", a: "Reversed as UTF-16 code units. Some combined emoji may split." }],
    ["text-sorter", "case-converter", "word-counter"],
  ),
  t(
    "text-to-slug",
    "Text to Slug",
    "text",
    "text",
    "Text  /  Slug",
    "Convert text to a URL slug",
    "Lowercase, hyphenated, ASCII-ish. For post titles and filenames.",
    ["slug generator", "text to slug", "permalink generator"],
    [{ q: "Unicode?", a: "Accents are stripped via NFKD. Remaining non-word characters are removed." }],
    ["url-encoder-decoder", "case-converter", "remove-extra-spaces"],
  ),
  t(
    "url-encoder-decoder",
    "URL Encoder / Decoder",
    "text",
    "text",
    "Text  /  URL",
    "Encode or decode a URL",
    "encodeURIComponent and decodeURIComponent in this tab.",
    ["url encoder", "url decoder", "percent encode"],
    [{ q: "Plus signs?", a: "On decode, + becomes a space (form style). Encode uses %20." }],
    ["base64-encoder-decoder", "text-to-slug", "json-formatter"],
  ),
  t(
    "base64-encoder-decoder",
    "Base64 Encoder / Decoder",
    "text",
    "text",
    "Text  /  Base64",
    "Encode or decode Base64",
    "UTF-8 text to Base64 and back. For images, use Image to Base64.",
    ["base64 encoder", "base64 decoder", "encode base64"],
    [{ q: "Files?", a: "This page is text. Open Image to Base64 for a data URL from a photo." }],
    ["image-to-base64", "url-encoder-decoder", "json-formatter"],
  ),
  t(
    "json-formatter",
    "JSON Formatter",
    "text",
    "text",
    "Text  /  JSON",
    "Format JSON",
    "Pretty-print with 2-space indent. Invalid JSON shows the parser error.",
    ["json formatter", "json pretty print", "beautify json"],
    [{ q: "Comments?", a: "Standard JSON has no comments. They will fail to parse." }],
    ["json-validator", "xml-formatter", "base64-encoder-decoder"],
  ),
  t(
    "json-validator",
    "JSON Validator",
    "text",
    "text",
    "Text  /  JSON",
    "Validate JSON",
    "JSON.parse in this tab. Tells you if it is valid and the engine error if not.",
    ["json validator", "validate json", "json lint"],
    [{ q: "Schema?", a: "No JSON Schema here — only parse validity." }],
    ["json-formatter", "xml-formatter", "html-formatter"],
  ),
  t(
    "xml-formatter",
    "XML Formatter",
    "text",
    "text",
    "Text  /  XML",
    "Format XML",
    "Parse with DOMParser and indent. Malformed XML is rejected.",
    ["xml formatter", "pretty xml", "beautify xml"],
    [{ q: "HTML?", a: "Use HTML Formatter for HTML5. This path is application/xml." }],
    ["html-formatter", "json-formatter", "markdown-to-html"],
  ),
  t(
    "html-formatter",
    "HTML Formatter",
    "text",
    "text",
    "Text  /  HTML",
    "Format HTML",
    "Indent HTML in this tab. The browser parser may normalise tags.",
    ["html formatter", "beautify html", "pretty html"],
    [{ q: "Will it fix broken HTML?", a: "The HTML parser is forgiving. Output may not match a byte-for-byte source file." }],
    ["html-minifier", "xml-formatter", "css-minifier"],
  ),
  t(
    "html-minifier",
    "HTML Minifier",
    "text",
    "text",
    "Text  /  Minify",
    "Minify HTML",
    "Strip comments and collapse whitespace. Not a full html-minifier pass.",
    ["html minifier", "minify html", "compress html"],
    [{ q: "Will <pre> survive?", a: "Whitespace collapse can squash preformatted blocks. Check before shipping." }],
    ["css-minifier", "js-minifier", "html-formatter"],
  ),
  t(
    "css-minifier",
    "CSS Minifier",
    "text",
    "text",
    "Text  /  Minify",
    "Minify CSS",
    "Strip comments and extra whitespace. Safe for straightforward stylesheets.",
    ["css minifier", "minify css", "compress css"],
    [{ q: "Is this cssnano?", a: "No. It does not rewrite selectors or merge rules." }],
    ["js-minifier", "html-minifier", "json-formatter"],
  ),
  t(
    "js-minifier",
    "JS Minifier",
    "text",
    "text",
    "Text  /  Minify",
    "Minify JavaScript",
    "Strip comments and extra whitespace. Not Terser — ASI-sensitive code can break.",
    ["js minifier", "minify javascript", "compress js"],
    [
      {
        q: "Production bundle?",
        a: "Use Terser or esbuild for real apps. This page is for small snippets you pasted.",
      },
    ],
    ["css-minifier", "html-minifier", "json-formatter"],
  ),
  t(
    "markdown-to-html",
    "Markdown to HTML",
    "text",
    "text",
    "Text  /  Markdown",
    "Convert Markdown to HTML",
    "Headings, lists, links, code, emphasis. A small local dialect — not CommonMark-complete.",
    ["markdown to html", "md to html", "convert markdown"],
    [{ q: "GFM tables?", a: "Not in this converter. Headings, lists, code fences, links, bold, italic, quotes." }],
    ["html-formatter", "html-minifier", "word-counter"],
  ),
  t(
    "photo-to-sketch",
    "Photo to Sketch",
    "edit",
    "image-fx",
    "Edit  /  Sketch",
    "Turn a photo into a pencil sketch",
    "Local dodge-blend sketch. Not an AI illustrator — contrasty photos work best.",
    ["photo to sketch", "pencil sketch filter", "drawing filter"],
    [{ q: "Is this AI?", a: "No. Grayscale, invert, blur, colour dodge on a canvas." }],
    ["photo-to-cartoon", "black-and-white", "image-enhancer"],
  ),
  t(
    "photo-to-cartoon",
    "Photo to Cartoon",
    "edit",
    "image-fx",
    "Edit  /  Cartoon",
    "Cartoon / posterise a photo",
    "Posterise colours and ink the edges. A filter, not a generative cartoonist.",
    ["photo to cartoon", "cartoon filter", "posterize photo"],
    [{ q: "Will it look like an app cartoon?", a: "It is posterise + Sobel edges. Faces will not become a licensed sticker pack." }],
    ["photo-to-sketch", "pixelate-image", "color-grading"],
  ),
  t(
    "pixelate-image",
    "Pixelate Image",
    "edit",
    "image-fx",
    "Edit  /  Pixel",
    "Pixelate an image",
    "Chunky blocks over the whole frame. For a region, use Mosaic / Censor.",
    ["pixelate image", "pixelate photo", "mosaic filter"],
    [{ q: "Whole image?", a: "Yes. Mosaic / Censor pixelates only the boxes you draw." }],
    ["mosaic-censor-image", "blur-image", "photo-to-cartoon"],
  ),
  t(
    "blur-image",
    "Blur Image",
    "edit",
    "image-fx",
    "Edit  /  Blur",
    "Blur an image",
    "Gaussian-style canvas blur on the whole photo.",
    ["blur image", "blur photo online", "gaussian blur"],
    [{ q: "Faces only?", a: "Use Blur Face and drag boxes (or Detect faces in Chromium)." }],
    ["blur-face", "pixelate-image", "mosaic-censor-image"],
  ),
  t(
    "blur-face",
    "Blur Face",
    "edit",
    "image-fx",
    "Edit  /  Privacy",
    "Blur faces in a photo",
    "Drag boxes over faces. Chromium may auto-detect. Local blur — no cloud face API.",
    ["blur face", "censor face", "anonymize photo"],
    [
      {
        q: "Auto-detect?",
        a: "Uses the browser FaceDetector where it exists (often Chrome). Otherwise drag boxes. We do not call a face-recognition service.",
      },
    ],
    ["mosaic-censor-image", "blur-image", "exif-metadata-remover"],
  ),
  t(
    "mosaic-censor-image",
    "Mosaic / Censor Image",
    "edit",
    "image-fx",
    "Edit  /  Censor",
    "Pixelate / censor part of an image",
    "Draw boxes to mosaic plates, screens, or faces. Processed here.",
    ["censor image", "mosaic photo", "pixelate area"],
    [{ q: "Undo a box?", a: "Reload the photo to clear boxes, then redraw." }],
    ["blur-face", "pixelate-image", "photo-cropper"],
  ),
  t(
    "collage-maker",
    "Collage Maker",
    "edit",
    "image-fx",
    "Edit  /  Collage",
    "Make a photo collage",
    "2×2, 3×3, and strips. Cover-fit cells. Download JPEG or PNG.",
    ["collage maker", "photo collage", "image grid"],
    [{ q: "Custom layout?", a: "Pick a grid. Fine artboards still want a desktop layout app." }],
    ["image-joiner", "meme-generator", "photo-border-maker"],
    { multiple: true },
  ),
  t(
    "meme-generator",
    "Meme Generator",
    "edit",
    "image-fx",
    "Edit  /  Meme",
    "Add meme captions to a photo",
    "Impact-style top and bottom text, stroked for contrast. Local.",
    ["meme generator", "caption meme", "impact font meme"],
    [{ q: "Font?", a: "Impact if installed, otherwise Arial Black. Text is drawn on the pixels." }],
    ["photo-border-maker", "collage-maker", "add-watermark"],
  ),
  t(
    "image-splitter",
    "Image Splitter",
    "edit",
    "image-fx",
    "Edit  /  Split",
    "Split an image into a grid",
    "Rows × columns, then a ZIP of tiles.",
    ["image splitter", "slice image", "split photo grid"],
    [{ q: "Remainder pixels?", a: "Tiles are floor-divided. A leftover strip on the right/bottom is dropped." }],
    ["image-joiner", "photo-cropper", "collage-maker"],
  ),
  t(
    "image-joiner",
    "Image Joiner",
    "edit",
    "image-fx",
    "Edit  /  Join",
    "Join images horizontally or vertically",
    "Stitch photos into one strip. Heights (or widths) are matched.",
    ["image joiner", "merge images", "combine photos"],
    [{ q: "Different sizes?", a: "Each piece is scaled to the tallest (horizontal) or widest (vertical) image." }],
    ["image-splitter", "collage-maker", "jpg-to-pdf"],
    { multiple: true },
  ),
  t(
    "photo-border-maker",
    "Photo Border Maker",
    "edit",
    "image-fx",
    "Edit  /  Border",
    "Add a border to a photo",
    "Pick width and colour. The frame is extra pixels, not a CSS overlay.",
    ["photo border", "add border to image", "picture frame"],
    [{ q: "Polaroid?", a: "Use a thick light border; this tool does not draw a caption strip." }],
    ["rounded-image", "meme-generator", "add-watermark"],
  ),
  t(
    "rounded-image",
    "Rounded Image",
    "edit",
    "image-fx",
    "Edit  /  Round",
    "Round the corners of an image",
    "PNG with transparent corners. Set the radius in pixels.",
    ["rounded image", "round corners photo", "border radius image"],
    [{ q: "JPEG?", a: "Corners need transparency — export is PNG." }],
    ["circle-crop", "photo-cropper", "photo-border-maker"],
  ),
  t(
    "circle-crop",
    "Circle Crop",
    "edit",
    "image-fx",
    "Edit  /  Circle",
    "Crop a photo to a circle",
    "Cover-fit into a circle, PNG with a transparent outside. For avatars.",
    ["circle crop", "round crop photo", "avatar crop"],
    [{ q: "Exact millimetres?", a: "This is a pixel circle. Passport specs still live on the document-photo pages." }],
    ["rounded-image", "photo-cropper", "passport-photo-maker"],
  ),
  t(
    "exif-metadata-remover",
    "EXIF Metadata Remover",
    "edit",
    "exif",
    "Edit  /  Exif",
    "Remove EXIF metadata from a photo",
    "Strip camera, GPS, and other APP segments from a JPEG without recompressing when possible.",
    ["exif remover", "remove gps from photo", "strip metadata", "remove exif gps"],
    [
      {
        q: "PNG / WebP / HEIC?",
        a: "Those are re-encoded to JPEG without metadata. JPEG keeps the original coefficients when we only drop APP/COM markers.",
      },
    ],
    ["exif-metadata-viewer", "blur-face", "compress-image"],
  ),
  t(
    "exif-metadata-viewer",
    "EXIF Metadata Viewer",
    "edit",
    "exif",
    "Edit  /  Exif",
    "View EXIF metadata",
    "Make, model, date, ISO, GPS if the JPEG stored them. Nothing is uploaded.",
    ["exif viewer", "view photo metadata", "gps from photo"],
    [{ q: "No tags?", a: "Screenshots and many chat apps already stripped Exif. File name and size still show." }],
    ["exif-metadata-remover", "image-to-base64", "compress-image"],
  ),
];
