import type { NextConfig } from "next";

const toFinance = (slug: string) => ({
  source: `/tools/${slug}`,
  destination: `/finance/${slug}`,
  permanent: true,
});

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,
  serverExternalPackages: ["tesseract.js"],
  async redirects() {
    return [
      toFinance("ireland-mortgage-calculator"),
      toFinance("ireland-mortgage-repayment-calculator"),
      toFinance("loan-repayment-calculator-ireland"),
      toFinance("northern-ireland-mortgage-calculator"),
      toFinance("holiday-let-mortgage-calculator-ireland"),
      toFinance("mortgage-calculator"),
      toFinance("mortgage-repayment-calculator"),
      toFinance("home-improvement-loan-calculator"),
      toFinance("irpef-italy"),
      toFinance("uae-salary-calculator"),
      toFinance("dubai-salary-calculator"),
      toFinance("nz-tax-calculator"),
      toFinance("take-home-pay-calculator"),
      toFinance("salary-calculator"),
      toFinance("transfer-duty-calculator"),
      toFinance("percent-to-money"),
      toFinance("chile-income-tax-calculator"),
      toFinance("south-africa-transfer-duty-calculator"),
      toFinance("cpf-calculator"),
      toFinance("cpf-contribution-calculator"),
      toFinance("cpf-rate-calculator"),
      toFinance("singapore-cpf-calculator"),
      toFinance("danske-mortgage-calculator"),
      toFinance("emi-calculator-ireland"),
      toFinance("mortgage-top-up-calculator"),
      toFinance("after-tax-income-calculator"),
      toFinance("percentage-return-calculator"),
      toFinance("monthly-salary-calculator-uae"),
      toFinance("uk-council-tax-calculator"),
      toFinance("investment-return-calculator"),
      {
        source: "/tools/online-mortgage-calculator-donegal",
        destination: "/finance/ireland-mortgage-calculator",
        permanent: true,
      },
      {
        source: "/tools/mortgage-calculator-ie",
        destination: "/finance/ireland-mortgage-calculator",
        permanent: true,
      },
      { source: "/tools/compress-pdf-to-2mn", destination: "/tools/compress-pdf-to-2mb", permanent: true },
      { source: "/tools/compress-pdf-to-2m", destination: "/tools/compress-pdf-to-2mb", permanent: true },
      { source: "/tools/compress-pdf-tp-2mb", destination: "/tools/compress-pdf-to-2mb", permanent: true },
      { source: "/tools/compress-pdf-to-1-mg", destination: "/tools/compress-pdf-to-1mb", permanent: true },
      { source: "/tools/pdf-2mp-converter", destination: "/tools/compress-pdf-to-2mb", permanent: true },
      { source: "/tools/dpi-coverter", destination: "/tools/dpi-converter", permanent: true },
      { source: "/tools/dpi-convereter", destination: "/tools/dpi-converter", permanent: true },
      { source: "/tools/dpi-conerter", destination: "/tools/dpi-converter", permanent: true },
      { source: "/tools/dip-converter", destination: "/tools/dpi-converter", permanent: true },
      { source: "/tools/singnature-resize", destination: "/tools/signature-resize", permanent: true },
      { source: "/tools/signatureresize", destination: "/tools/signature-resizer", permanent: true },
      { source: "/tools/sing-resizer", destination: "/tools/signature-resizer", permanent: true },
      { source: "/tools/resize-adhar", destination: "/tools/aadhar-card-resize", permanent: true },
      { source: "/tools/compress-aadhar", destination: "/tools/compress-aadhaar-pdf", permanent: true },
      { source: "/tools/pakistani-driving-license-picture", destination: "/tools/driving-licence-photo-pakistan", permanent: true },
      { source: "/tools/license-picture-pakistan", destination: "/tools/driving-licence-photo-pakistan", permanent: true },
      { source: "/tools/driving-license-pic-pakistan", destination: "/tools/driving-licence-photo-pakistan", permanent: true },
      { source: "/tools/driving-license-photo-pakistan", destination: "/tools/driving-licence-photo-pakistan", permanent: true },
      { source: "/tools/pakistani-license-pic", destination: "/tools/driving-licence-photo-pakistan", permanent: true },
      { source: "/tools/green-card-maker", destination: "/tools/us-green-card-photo", permanent: true },
      { source: "/tools/green-card-generator", destination: "/tools/us-green-card-photo", permanent: true },
      { source: "/tools/pakistan-cnic-maker", destination: "/tools/pakistan-cnic-photo-resize", permanent: true },
      { source: "/tools/make-cancelled-cheque", destination: "/tools/cancelled-cheque-image", permanent: true },
      { source: "/tools/create-cancelled-cheque", destination: "/tools/cancelled-cheque-image", permanent: true },
      { source: "/tools/dummy-cancelled-cheque", destination: "/tools/cancelled-cheque-image", permanent: true },
      { source: "/tools/make-cancelled-cheque-online", destination: "/tools/cancelled-cheque-image", permanent: true },
      { source: "/tools/51x51mm-photo-size", destination: "/tools/51-mm-x-51-mm-photo", permanent: true },
      { source: "/tools/photo-35-x-45-mm", destination: "/tools/35-x-45-mm-photo", permanent: true },
      { source: "/tools/35x45mm-in-px", destination: "/tools/35-x-45-mm-photo", permanent: true },
      { source: "/tools/b2-size-photo-for-marriage-certificate", destination: "/tools/marriage-certificate-photo", permanent: true },
      { source: "/tools/jpeg-to-png-converter", destination: "/tools/jpg-to-png-converter", permanent: true },
      { source: "/tools/turn-a-photo-black-and-white", destination: "/tools/image-to-black-and-white", permanent: true },
      { source: "/tools/chroma-key-online-image", destination: "/tools/chroma-key-online", permanent: true },
      { source: "/tools/video-keyer", destination: "/tools/online-chroma-keyer", permanent: true },
      { source: "/tools/change-video-color-online-free", destination: "/tools/video-colour-grading-online", permanent: true },
      { source: "/tools/color-balancer", destination: "/tools/colour-grading-online", permanent: true },
      { source: "/tools/convert-image-to-72-dpi", destination: "/tools/dpi-converter", permanent: true },
      { source: "/tools/100-dpi-converter", destination: "/tools/dpi-converter", permanent: true },
      { source: "/tools/1200-dpi-converter", destination: "/tools/image-to-600-dpi", permanent: true },
      { source: "/tools/nid-converter", destination: "/tools/nid-card-resize", permanent: true },
      { source: "/tools/nid-card-resize-online", destination: "/tools/nid-card-resize", permanent: true },
      { source: "/tools/diy-passport-photo-australia", destination: "/tools/australian-passport-photo-online", permanent: true },
      { source: "/tools/passport-photo-online-australia", destination: "/tools/australian-passport-photo-online", permanent: true },
      { source: "/tools/80k-take-home-pay", destination: "/finance/take-home-pay-calculator", permanent: true },
      { source: "/tools/26k-take-home-pay", destination: "/finance/take-home-pay-calculator", permanent: true },
      { source: "/tools/take-home-pay-35000", destination: "/finance/take-home-pay-calculator", permanent: true },
      { source: "/finance/80k-take-home-pay", destination: "/finance/take-home-pay-calculator", permanent: true },
      { source: "/tools/cpfcalculator", destination: "/finance/cpf-calculator", permanent: true },
      { source: "/tools/cpf-calculator-singapore", destination: "/finance/cpf-calculator", permanent: true },
      { source: "/tools/cpf-contribution-rate-calculator", destination: "/finance/cpf-contribution-calculator", permanent: true },
      { source: "/tools/cpf-deduction-calculator", destination: "/finance/cpf-contribution-calculator", permanent: true },
      { source: "/tools/council-tax-calculator-uk", destination: "/finance/uk-council-tax-calculator", permanent: true },
      { source: "/tools/uk-council-tax-calculator", destination: "/finance/uk-council-tax-calculator", permanent: true },
      { source: "/tools/morgage-calculator", destination: "/finance/mortgage-calculator", permanent: true },
      { source: "/tools/calculator-mortgage", destination: "/finance/mortgage-calculator", permanent: true },
      { source: "/tools/online-mortgage-calculator", destination: "/finance/mortgage-calculator", permanent: true },
      { source: "/tools/republic-of-ireland-mortgage-calculator", destination: "/finance/ireland-mortgage-calculator", permanent: true },
      { source: "/tools/irish-mortgage-calculator-ireland", destination: "/finance/ireland-mortgage-calculator", permanent: true },
      { source: "/tools/mortgage-loan-calculator-ireland", destination: "/finance/ireland-mortgage-calculator", permanent: true },
      { source: "/tools/mortgage-payment-calculator-ireland", destination: "/finance/ireland-mortgage-repayment-calculator", permanent: true },
      { source: "/tools/calculate-mortgage-repayments-ireland", destination: "/finance/ireland-mortgage-repayment-calculator", permanent: true },
      { source: "/tools/repayment-calculator-ireland", destination: "/finance/ireland-mortgage-repayment-calculator", permanent: true },
      { source: "/tools/home-loan-calculator-ireland", destination: "/finance/emi-calculator-ireland", permanent: true },
      { source: "/tools/mortgage-calculator-ireland-repayments", destination: "/finance/ireland-mortgage-repayment-calculator", permanent: true },
      { source: "/tools/repayments-on-100k-mortgage-ireland", destination: "/finance/ireland-mortgage-calculator", permanent: true },
      { source: "/tools/repayments-on-200k-mortgage-ireland", destination: "/finance/ireland-mortgage-calculator", permanent: true },
      { source: "/tools/pdf500", destination: "/tools/compress-pdf-to-500kb", permanent: true },
      { source: "/tools/pdf-500", destination: "/tools/compress-pdf-to-500kb", permanent: true },
      { source: "/tools/1-mb", destination: "/tools/compress-pdf-to-1mb", permanent: true },
      { source: "/tools/1-mb-pdf", destination: "/tools/compress-pdf-to-1mb", permanent: true },
      { source: "/tools/pdf-2mb", destination: "/tools/compress-pdf-to-2mb", permanent: true },
      { source: "/tools/jpeg-png-converter", destination: "/tools/jpg-to-png-converter", permanent: true },
      { source: "/tools/jpeg-to-png-convertor", destination: "/tools/jpg-to-png-converter", permanent: true },
      { source: "/tools/jpg-convert-in-png", destination: "/tools/jpg-to-png-converter", permanent: true },
      { source: "/tools/600-dpi-converter", destination: "/tools/image-to-600-dpi", permanent: true },
      { source: "/tools/free-online-dpi-converter", destination: "/tools/dpi-converter", permanent: true },
      { source: "/tools/convert-qr", destination: "/tools/qr-converter", permanent: true },
      { source: "/tools/blur-faces-online", destination: "/tools/blur-face-online", permanent: true },
      { source: "/tools/photo-resizer", destination: "/tools/photo-resize", permanent: true },
      { source: "/tools/signature-size-reducer", destination: "/tools/signature-resizer", permanent: true },
      { source: "/tools/passport-photo-service", destination: "/tools/passport-photo-maker", permanent: true },
      { source: "/tools/absolute-return-calculator", destination: "/finance/percentage-return-calculator", permanent: true },
      { source: "/tools/transfer-calculator", destination: "/finance/transfer-duty-calculator", permanent: true },
      { source: "/finance/transfer-calculator", destination: "/finance/transfer-duty-calculator", permanent: true },
    ];
  },
};

export default nextConfig;
